start psexec \\IS-M430M27-01 -c -v -d -s -i ../utorrent.exe /NOINSTALL /DIRECTORY "C:\Program Files (x86)\Steam\Steamapps\common\" \\IS-M440M27-21\gamenight\CSGOFOREALZ.torrent
start psexec \\IS-M430M27-02 -c -v -d -s -i ../utorrent.exe /NOINSTALL /DIRECTORY "C:\Program Files (x86)\Steam\Steamapps\common\" \\IS-M440M27-21\gamenight\CSGOFOREALZ.torrent
start psexec \\IS-M430M27-03 -c -v -d -s -i ../utorrent.exe /NOINSTALL /DIRECTORY "C:\Program Files (x86)\Steam\Steamapps\common\" \\IS-M440M27-21\gamenight\CSGOFOREALZ.torrent
start psexec \\IS-M430M27-04 -c -v -d -s -i ../utorrent.exe /NOINSTALL /DIRECTORY "C:\Program Files (x86)\Steam\Steamapps\common\" \\IS-M440M27-21\gamenight\CSGOFOREALZ.torrent
start psexec \\IS-M430M27-05 -c -v -d -s -i ../utorrent.exe /NOINSTALL /DIRECTORY "C:\Program Files (x86)\Steam\Steamapps\common\" \\IS-M440M27-21\gamenight\CSGOFOREALZ.torrent
start psexec \\IS-M430M27-06 -c -v -d -s -i ../utorrent.exe /NOINSTALL /DIRECTORY "C:\Program Files (x86)\Steam\Steamapps\common\" \\IS-M440M27-21\gamenight\CSGOFOREALZ.torrent
start psexec \\IS-M430M27-07 -c -v -d -s -i ../utorrent.exe /NOINSTALL /DIRECTORY "C:\Program Files (x86)\Steam\Steamapps\common\" \\IS-M440M27-21\gamenight\CSGOFOREALZ.torrent
start psexec \\IS-M430M27-08 -c -v -d -s -i ../utorrent.exe /NOINSTALL /DIRECTORY "C:\Program Files (x86)\Steam\Steamapps\common\" \\IS-M440M27-21\gamenight\CSGOFOREALZ.torrent
start psexec \\IS-M430M27-09 -c -v -d -s -i ../utorrent.exe /NOINSTALL /DIRECTORY "C:\Program Files (x86)\Steam\Steamapps\common\" \\IS-M440M27-21\gamenight\CSGOFOREALZ.torrent
start psexec \\IS-M430M27-10 -c -v -d -s -i ../utorrent.exe /NOINSTALL /DIRECTORY "C:\Program Files (x86)\Steam\Steamapps\common\" \\IS-M440M27-21\gamenight\CSGOFOREALZ.torrent
start psexec \\IS-M430M27-12 -c -v -d -s -i ../utorrent.exe /NOINSTALL /DIRECTORY "C:\Program Files (x86)\Steam\Steamapps\common\" \\IS-M440M27-21\gamenight\CSGOFOREALZ.torrent
start psexec \\IS-M430M27-13 -c -v -d -s -i ../utorrent.exe /NOINSTALL /DIRECTORY "C:\Program Files (x86)\Steam\Steamapps\common\" \\IS-M440M27-21\gamenight\CSGOFOREALZ.torrent
start psexec \\IS-M430M27-14 -c -v -d -s -i ../utorrent.exe /NOINSTALL /DIRECTORY "C:\Program Files (x86)\Steam\Steamapps\common\" \\IS-M440M27-21\gamenight\CSGOFOREALZ.torrent
start psexec \\IS-M430M27-15 -c -v -d -s -i ../utorrent.exe /NOINSTALL /DIRECTORY "C:\Program Files (x86)\Steam\Steamapps\common\" \\IS-M440M27-21\gamenight\CSGOFOREALZ.torrent
start psexec \\IS-M430M27-16 -c -v -d -s -i ../utorrent.exe /NOINSTALL /DIRECTORY "C:\Program Files (x86)\Steam\Steamapps\common\" \\IS-M440M27-21\gamenight\CSGOFOREALZ.torrent
start psexec \\IS-M430M27-17 -c -v -d -s -i ../utorrent.exe /NOINSTALL /DIRECTORY "C:\Program Files (x86)\Steam\Steamapps\common\" \\IS-M440M27-21\gamenight\CSGOFOREALZ.torrent
start psexec \\IS-M430M27-18 -c -v -d -s -i ../utorrent.exe /NOINSTALL /DIRECTORY "C:\Program Files (x86)\Steam\Steamapps\common\" \\IS-M440M27-21\gamenight\CSGOFOREALZ.torrent